apiVersion: 1

deleteDatasources:
  - name: prometheus-docker-java

datasources:
  - name: prometheus-docker-java
    type: prometheus
    access: proxy
    url: http://prometheus-container:9090
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    editable: true